"""add image_url to animals

Revision ID: bba22ab434e2
Revises: 2375571466e3
Create Date: 2026-08-27 16:00:28.952451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bba22ab434e2'
down_revision = '2375571466e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # order_items has pre-existing foreign keys (order_id, animal_id) that
    # were declared inline on the model without explicit names. SQLite has
    # no native ALTER TABLE support, so Alembic rebuilds the whole table in
    # batch mode — which means it has to enumerate every existing
    # constraint, and it refuses to do that for an unnamed one. Passing a
    # naming_convention here lets it generate deterministic names for those
    # pre-existing constraints so the rebuild can proceed.
    naming_convention = {
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    }
    with op.batch_alter_table('order_items', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.add_column(sa.Column('farmer_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False))
        batch_op.create_foreign_key('fk_order_items_farmer_id_users', 'users', ['farmer_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.String(), nullable=True))
        batch_op.create_unique_constraint('uq_orders_order_number', ['order_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('uq_orders_order_number', type_='unique')
        batch_op.drop_column('order_number')

    naming_convention = {
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    }
    with op.batch_alter_table('order_items', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint('fk_order_items_farmer_id_users', type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('farmer_id')

    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###